
export const message={
    USERNOTLOGGEDIN:"USER NOT LOGGED IN",
    USERNOTSIGNEDUP:'USER NOT SIGNED UP',
    UNAUTHORIZEDACCESS:'UNAUTHORIZED ACCESS',
    INVALIDCREDENTIALS:'INVALID CREDENTIALS',
    USERSIGNEDUP:'USER SUCESSFULLY SIGNEDUP',
    USERLOGGEDIN:'USER LOGGED IN SUCCESSFULLY',
    USERLOGEDDOUT:'USER LOGGED OUT SUCCESSFULLY',
    USERUPDATED:'USER UPDATED SUCCESSFULLY',
    USERDELETED:'USER DELETED SUCCESFULLY',
    TOKENNOTVERIFIED:'TOKEN NOT VERIFIED',
    INTERNALSERVERORR:'INTERNAL SERVER ERROR',
    USERNOTFOUND:'USER NOT FOUND',


    EVENTCREATED:"EVENT SUCCESSFULLY CREATED",
    EVENTUPDATED:"EVENT SUCCESSFULLY UPDATED",
    EVENTDELETED:"EVENT SUCESSFULLY DELETED",
    EVENTNOTFOUND:"EVENTNOTFOUND",


    EVENTREGISTERED:"EVENT REGISTERED SUCESSFULLY",
    REGISTEREDEVENTNOTFOUND:"REGISTERED EVENET NOT FOUND"
}